---
title: "Analysis of GSE33126"
output: html_notebook
---

```{r message=FALSE}
library(GEOquery)
## can change the url to be the dataset that you want.

url <- "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE33nnn/GSE33126/matrix/GSE33126_series_matrix.txt.gz"

download.file(url, destfile = "GSE33126_series_matrix.txt.gz")

gse <- getGEO(filename = "GSE33126_series_matrix.txt.gz")

```


```{r}
## exprs get the expression levels as a data frame and get the distribution
summary(exprs(gse))
```


```{r}
normData <- log2(exprs(gse))

# the parameter outline=FALSE stops outliers being displayed on the plot - making it a bit tidier
boxplot(normData,outline=FALSE)
```

```{r}
library(dplyr)
sampleInfo <- pData(gse)
sampleInfo

## source_name_ch1 and characteristics_ch1.1 seem to contain factors we might need for the analysis. Let's pick just those columns

sampleInfo <- select(sampleInfo, source_name_ch1,characteristics_ch1.1)

## Optionally, rename to more convenient column names
sampleInfo <- rename(sampleInfo,group = source_name_ch1, patient=characteristics_ch1.1)
```




```{r}
library(genefilter)
fac <- as.factor(sampleInfo$group)
test_results <- rowttests(normData, fac)
head(test_results)
```



```{r}
## dplyr doesn't like rownames. Instead add the probe IDs to a column in the data frame

test_results <- tibble::rownames_to_column(test_results,"ID")
```


```{r}
anno <- fData(gse)
anno <- select(anno,Symbol,Entrez_Gene_ID,Chromosome,Cytoband)
anno <- tibble::rownames_to_column(anno,"ID")
test_results <- left_join(test_results,anno)
```


```{r}
arrange(test_results, p.value)
```

# Exercise 1

```{r}
test_results <- 
  mutate(test_results, padj = p.adjust(p.value, method="BH"))
sum(test_results$padj < 0.05)
```


```{r}
library(readr)
filter(test_results, p.value < 0.05, abs(dm) > 1) %>%
  write_csv(path="filtered_de_results.csv")
```

# Exercise 2


```{r}
library(ggplot2)
test_results <- 
  mutate(test_results, M = rowMeans(normData))
ggplot(test_results, aes(x = M, y = dm)) + geom_point() + geom_hline(yintercept = c(-1,1),col="red",lty=2)

```

# Weekly exercise

```{r}
filter(test_results, Chromosome != "", Cytoband != "") %>% 
arrange(Chromosome,Cytoband)
```

```{r}
mutate(test_results, Significant = padj < 0.05) %>% 
ggplot(aes(x = dm , y = -log10(p.value),col=Significant)) + geom_point() + scale_color_manual(values=c("black","red"))
```

