---
title: "R Notebook"
output: html_notebook
---

We start by loading our results from the previous week

```{r}
library(DESeq2)
library(dplyr)
## Read the counts that we produced previously
dds <- readRDS("Robjects/dds.rds")
results_cellType <- readRDS("Robjects/results_cellType.rds")
```

```{r}
library(org.Mm.eg.db)

anno <- AnnotationDbi::select(org.Mm.eg.db,keys=results_status$ENSEMBL,
              columns=c("ENSEMBL","SYMBOL","GENENAME","ENTREZID"),
              keytype="ENSEMBL") %>% 
  filter(!duplicated(ENSEMBL))
results_annotated <- left_join(results_cellType, anno,by="ENSEMBL") %>% 
  arrange(padj)
```

```{r}
library(ggplot2)
library(dplyr)
dds <- readRDS("Robjects/dds.rds")

plotCounts(dds, "ENSMUSG00000027750",intgroup = "CellType",returnData = TRUE) %>% 
  ggplot(aes(x = CellType, y = count,col=CellType)) + geom_jitter(width=0.1) + scale_y_log10()

```

```{r}
library(pheatmap)
results_status <- readRDS("Robjects/results_status.rds")
results_annotated <- left_join(results_status, anno,by="ENSEMBL") %>% 
  arrange(padj)
top_genes <- results_annotated$ENSEMBL[1:10]
sampleInfo <- as.data.frame(colData(dds)[,c("Status","CellType")])

vsd <- vst(dds)
pheatmap(assay(vsd)[top_genes,],
         annotation_col = sampleInfo,scale="row")
```

```{r}
go_genes <- unique(AnnotationDbi::select(org.Mm.eg.db, keys="GO:0071850",keytype="GO",columns="ENSEMBL")$ENSEMBL)
library(pheatmap)
vsd <- vst(dds)
pheatmap(assay(vsd)[go_genes,], 
         annotation_col = sampleInfo,
         scale="row")

```